# Generated by Django 4.2.1 on 2023-09-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='password',
            new_name='password_id',
        ),
    ]
