# Generated by Django 4.2.1 on 2023-09-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_rename_password_programs_password_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='password_id',
            new_name='password',
        ),
    ]
