# Generated by Django 4.2.1 on 2023-09-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_rename_password_id_programs_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='password',
            new_name='programs_id',
        ),
    ]
