# Generated by Django 4.2.1 on 2023-09-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_rename_password_programs_programs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='programs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='asosiy.password'),
        ),
    ]
